/* Bilingual teaching glossary. Headwords checked against Cambridge YLE wordlists (2025).
   Translations and teaching examples are original. Variant spellings share an entry.
   Stable word IDs must not depend on row order. */
(function () {
  'use strict';
  const groups = [
    ['starters', 'family', 1, `baby=em bé;boy=bé trai;brother=anh, em trai;child=đứa trẻ;classmate=bạn cùng lớp;cousin=anh chị em họ;dad=bố;family=gia đình;father=cha;friend=bạn;girl=bé gái;grandfather=ông;grandma=bà;grandmother=bà;grandpa=ông;kid=trẻ em;live=sống;man=người đàn ông;mother=mẹ;mum=mẹ;old=già, cũ;person=người;sister=chị, em gái;woman=người phụ nữ;young=trẻ tuổi`],
    ['starters', 'home', 1, `apartment=căn hộ;armchair=ghế bành;bath=bồn tắm;bathroom=phòng tắm;bed=giường;bedroom=phòng ngủ;bookcase=tủ sách;box=hộp;chair=ghế;clock=đồng hồ treo tường;cupboard=tủ đựng đồ;desk=bàn học;dining room=phòng ăn;door=cửa ra vào;floor=sàn nhà;garden=vườn;hall=sảnh;home=nhà, ở nhà;house=ngôi nhà;kitchen=nhà bếp;lamp=đèn;living room=phòng khách;mat=tấm thảm nhỏ;mirror=gương;room=phòng;rug=thảm trải sàn;sofa=ghế sofa;table=bàn;wall=tường;window=cửa sổ`],
    ['starters', 'school', 1, `alphabet=bảng chữ cái;answer=câu trả lời, trả lời;board=bảng;book=sách;bookshop=hiệu sách;class=lớp học;classroom=phòng học;computer=máy tính;crayon=bút sáp;cross=dấu gạch chéo, gạch chéo;drawing=bức vẽ;English=tiếng Anh;eraser=cục tẩy;example=ví dụ;keyboard=bàn phím;learn=học;lesson=bài học;letter=chữ cái;line=đường kẻ;number=số;page=trang;paper=giấy;part=phần;pen=bút mực;pencil=bút chì;picture=bức tranh;playground=sân chơi;poster=áp phích;question=câu hỏi;ruler=thước kẻ;school=trường học;sentence=câu;story=câu chuyện;teacher=giáo viên;tick=dấu tích, đánh dấu tích;word=từ`],
    ['starters', 'animals', 2, `animal=động vật;bear=gấu;bee=ong;bird=chim;cat=mèo;chicken=gà, thịt gà;cow=bò;crocodile=cá sấu;dog=chó;donkey=lừa;duck=vịt;elephant=voi;fish=cá;frog=ếch;giraffe=hươu cao cổ;goat=dê;hippo=hà mã;horse=ngựa;jellyfish=sứa;lizard=thằn lằn;monkey=khỉ;mouse=chuột;pet=thú cưng;polar bear=gấu Bắc Cực;sheep=cừu;snake=rắn;spider=nhện;tail=đuôi;tiger=hổ;zebra=ngựa vằn;zoo=sở thú`],
    ['starters', 'food', 3, `apple=táo;banana=chuối;bean=đậu;bread=bánh mì;breakfast=bữa sáng;burger=bánh mì kẹp thịt;cake=bánh ngọt;candy=kẹo;carrot=cà rốt;chips=khoai tây chiên;chocolate=sô cô la;coconut=dừa;dinner=bữa tối;drink=đồ uống, uống;eat=ăn;egg=trứng;food=thức ăn;fruit=trái cây;grape=nho;ice cream=kem;juice=nước ép;kiwi=quả kiwi;lemon=chanh vàng;lemonade=nước chanh;lime=chanh xanh;lunch=bữa trưa;mango=xoài;meat=thịt;meatballs=thịt viên;milk=sữa;onion=hành tây;orange=cam, màu cam;pea=hạt đậu Hà Lan;pear=lê;pie=bánh có nhân;pineapple=dứa;potato=khoai tây;rice=cơm, gạo;sausage=xúc xích;tomato=cà chua;water=nước;watermelon=dưa hấu`],
    ['starters', 'transport', 4, `bike=xe đạp;boat=thuyền;bus=xe buýt;car=ô tô;drive=lái xe;fly=bay;go=đi;helicopter=máy bay trực thăng;lorry=xe tải;motorbike=xe máy;plane=máy bay;ride=cưỡi, đi xe;run=chạy;ship=tàu thủy;swim=bơi;train=tàu hỏa`],
    ['starters', 'sport', 5, `alien=người ngoài hành tinh;badminton=cầu lông;ball=bóng;balloon=bóng bay;baseball=bóng chày;basketball=bóng rổ;board game=trò chơi bàn cờ;camera=máy ảnh;doll=búp bê;fishing=câu cá;football=bóng đá;game=trò chơi;guitar=đàn ghi ta;hobby=sở thích;hockey=khúc côn cầu;kite=diều;monster=quái vật;music=âm nhạc;paint=sơn, vẽ bằng màu;painting=tranh vẽ bằng màu;phone=điện thoại, gọi điện;photo=ảnh;piano=đàn piano;play=chơi;radio=đài;robot=người máy;skateboard= ván trượt;skateboarding=môn trượt ván;song=bài hát;sport=thể thao;table tennis=bóng bàn;tablet=máy tính bảng;teddy bear=gấu bông;television=ti vi;tennis=quần vợt;tennis racket=vợt quần vợt;toy=đồ chơi`],
    ['starters', 'nature', 6, `beach=bãi biển;flower=hoa;park=công viên;sand=cát;sea=biển;shell=vỏ sò;street=đường phố;sun=mặt trời;tree=cây`],
    ['starters', 'body', 7, `arm=cánh tay;body=cơ thể;ear=tai;eye=mắt;face=khuôn mặt;foot=bàn chân;hair=tóc;hand=bàn tay;head=đầu;leg=chân;mouth=miệng;nose=mũi;smile=nụ cười, cười`],
    ['starters', 'clothes', 7, `bag=túi; basebalL cap=mũ bóng chày;boots=ủng;clothes=quần áo;dress=váy liền;glasses=kính;handbag=túi xách;hat=mũ;jacket=áo khoác;jeans=quần bò;shirt=áo sơ mi;shoe=giày;shorts=quần đùi;skirt=chân váy;sock=tất;trousers=quần dài;T-shirt=áo phông;wear=mặc, đeo`],
    ['starters', 'description', 7, `angry=tức giận;beautiful=đẹp;big=to;black=màu đen;blue=màu xanh dương;brown=màu nâu;clean=sạch, làm sạch;closed=đóng;colour=màu sắc, tô màu;cool=mát, tuyệt;correct=đúng;dirty=bẩn;double=gấp đôi;fantastic=tuyệt vời;favourite=yêu thích;fun=vui, niềm vui;funny=buồn cười;good=tốt;great=tuyệt;green=màu xanh lá;grey=màu xám;happy=vui vẻ;long=dài;new=mới;nice=dễ mến;pink=màu hồng;purple=màu tím;red=màu đỏ;right=đúng;sad=buồn;scary=đáng sợ;short=ngắn, thấp;silly=ngớ ngẩn;small=nhỏ;sorry=xin lỗi;ugly=xấu;white=màu trắng;yellow=màu vàng`],
    ['starters', 'time', 8, `afternoon=buổi chiều;birthday=sinh nhật;day=ngày;evening=buổi tối;morning=buổi sáng;night=ban đêm;today=hôm nay;year=năm`],
    ['starters', 'actions', 8, `add=cộng, thêm;ask=hỏi;be=thì, là, ở;bounce=nảy, làm nảy;can=có thể;catch=bắt, đón bóng;choose=chọn;clap=vỗ tay;close=đóng;come=đến;complete=hoàn thành;count=đếm;do=làm;draw=vẽ;enjoy=thích, tận hưởng;find=tìm thấy;get=lấy, nhận;give=đưa, cho;go to bed=đi ngủ;go to sleep=bắt đầu ngủ;have=có;have got=có;hit=đánh, đập;hold=cầm, giữ;jump=nhảy;kick=đá;know=biết;listen=nghe;look=nhìn;look at=nhìn vào;love=yêu, rất thích;make=làm, tạo;open=mở;pick up=nhặt lên;point=chỉ;put=đặt;read=đọc;say=nói;see=nhìn thấy;show=cho xem;sing=hát;sit=ngồi;sleep=ngủ;spell=đánh vần;stand=đứng;start=bắt đầu;stop=dừng;take a photo=chụp ảnh;talk=nói chuyện;tell=kể, bảo;throw=ném;try=thử;understand=hiểu;walk=đi bộ;want=muốn;watch=xem, đồng hồ đeo tay;wave=vẫy tay;would like=muốn một cách lịch sự;write=viết`],
    ['starters', 'language', 8, `a=một (trước phụ âm);about=về;again=lại;an=một (trước nguyên âm);and=và;at=ở, tại;behind=phía sau;between=ở giữa;but=nhưng;bye=tạm biệt;don't worry=đừng lo;end=kết thúc;for=cho;from=từ;goodbye=tạm biệt;he=anh ấy;hello=xin chào;her=của cô ấy, cô ấy;here=ở đây;hers=cái của cô ấy;hi=chào;him=anh ấy (tân ngữ);his=của anh ấy;hooray=hoan hô;how=như thế nào;how many=bao nhiêu (đếm được);how old=bao nhiêu tuổi;I=tôi;in=trong;in front of=phía trước;it=nó;its=của nó;let's=chúng ta hãy;like=thích, giống như;a lot=rất nhiều;a lot of=nhiều;lots=rất nhiều;lots of=nhiều;many=nhiều (đếm được);me=tôi (tân ngữ);me too=tôi cũng vậy;mine=cái của tôi;Miss=cô (danh xưng);Mr=ông (danh xưng);Mrs=bà (danh xưng);my=của tôi;name=tên;next to=bên cạnh;no=không;not=không (phủ định);now=bây giờ;of=của;oh=ồ;oh dear=ôi trời;OK=được, ổn;on=trên;one=một;or=hoặc;our=của chúng tôi;ours=cái của chúng tôi;pardon=xin nhắc lại;please=làm ơn;really=thật sự;see you=hẹn gặp lại;she=cô ấy;shop=cửa hàng;so=vậy thì;some=một ít;thank you=cảm ơn;thanks=cảm ơn (thân mật);that=cái kia;the=mạo từ xác định;their=của họ;theirs=cái của họ;them=họ (tân ngữ);then=sau đó;there=ở đó;these=những cái này;they=họ;thing=thứ, vật;this=cái này;those=những cái kia;to=đến;too=cũng, quá;under=bên dưới;us=chúng tôi (tân ngữ);very=rất;we=chúng tôi;well=ừ, tốt;well done=làm tốt lắm;what=cái gì;where=ở đâu;which=cái nào;who=ai;whose=của ai;with=với;wow=ồ, tuyệt;yes=có, vâng;you=bạn;your=của bạn;yours=cái của bạn`],
    ['movers', 'family', 1, `aunt=cô, dì, bác gái;daughter=con gái;granddaughter=cháu gái của ông bà;grandparent=ông hoặc bà;grandson=cháu trai của ông bà;grown-up=người lớn;parent=bố hoặc mẹ;son=con trai;uncle=chú, cậu, bác trai`],
    ['movers', 'home', 1, `balcony=ban công;basement=tầng hầm;blanket=chăn;downstairs=ở tầng dưới;roof=mái nhà;shower=vòi sen, lần tắm;stairs=cầu thang;toothbrush=bàn chải đánh răng;toothpaste=kem đánh răng;towel=khăn;upstairs=ở tầng trên`],
    ['movers', 'school', 1, `app=ứng dụng;break=giờ nghỉ;CD=đĩa CD;circle=hình tròn;comic=truyện tranh;comic book=cuốn truyện tranh;difference=sự khác biệt;DVD=đĩa DVD;e-book=sách điện tử;email=thư điện tử, gửi email;homework=bài tập về nhà;internet=mạng internet;laptop=máy tính xách tay;machine=máy móc;message=tin nhắn;mistake=lỗi;practice=sự luyện tập;practise=luyện tập;shape=hình dạng;square=hình vuông;teach=dạy;text=tin nhắn, nhắn tin;video=video, quay video;website=trang web`],
    ['movers', 'animals', 2, `bat=con dơi;cage=lồng;dolphin=cá heo;fly=con ruồi;kangaroo=chuột túi;kitten=mèo con;lion=sư tử;panda=gấu trúc;parrot=vẹt;penguin=chim cánh cụt;puppy=chó con;rabbit=thỏ;shark=cá mập;snail=ốc sên;whale=cá voi`],
    ['movers', 'nature', 2, `field=cánh đồng;forest=rừng;grass=cỏ;ground=mặt đất;island=đảo;jungle=rừng rậm;lake=hồ;leaf=lá;moon=mặt trăng;mountain=núi;plant=cây, trồng cây;river=sông;rock=tảng đá;sky=bầu trời;star=ngôi sao;waterfall=thác nước;wave=sóng;world=thế giới`],
    ['movers', 'food', 3, `bottle=chai;bowl=bát;cheese=phô mai;coffee=cà phê;cup=tách;glass=cốc thủy tinh;hungry=đói;milkshake=sữa lắc;noodles=mì;pancake=bánh kếp;pasta=mì Ý;picnic=buổi dã ngoại;plate=đĩa;salad=rau trộn;sandwich=bánh mì kẹp;sauce=nước xốt;soup=súp;tea=trà;thirsty=khát;vegetable=rau củ`],
    ['movers', 'health', 3, `cold=cảm lạnh, lạnh;cough=ho;cry=khóc;dentist=nha sĩ;doctor=bác sĩ;earache=đau tai;fall=ngã;fine=khỏe, ổn;headache=đau đầu;hospital=bệnh viện;hurt=đau, làm đau;ill=ốm;matter=vấn đề;nurse=y tá;sick=ốm;stomach-ache=đau bụng;temperature=nhiệt độ, cơn sốt;tired=mệt;toothache=đau răng`],
    ['movers', 'town', 4, `building=tòa nhà;bus station=bến xe buýt;bus stop=điểm dừng xe buýt;café=quán cà phê;car park=bãi đỗ xe;centre=trung tâm;cinema=rạp chiếu phim;city=thành phố;city centre=trung tâm thành phố;country=đất nước;countryside=nông thôn;driver=tài xế;elevator=thang máy;farm=nông trại;farmer=nông dân;library=thư viện;map=bản đồ;market=chợ;place=nơi chốn;road=đường;shopping centre=trung tâm mua sắm;sports centre=trung tâm thể thao;station=nhà ga;supermarket=siêu thị;town=thị trấn;town centre=trung tâm thị trấn;tractor=máy kéo;village=làng`],
    ['movers', 'position', 4, `above=phía trên;along=dọc theo;around=xung quanh;below=phía dưới;bottom=đáy, dưới cùng;by=bằng, bên cạnh;down=xuống;inside=bên trong;into=vào trong;near=gần;off=rời khỏi;opposite=đối diện;out=ra ngoài;out of=ra khỏi;outside=bên ngoài;round=tròn, vòng quanh;top=đỉnh, trên cùng;up=lên`],
    ['movers', 'sport', 5, `band=ban nhạc;circus=rạp xiếc;clown=chú hề;dance=điệu nhảy, nhảy;film=bộ phim, quay phim;film star=ngôi sao điện ảnh;funfair=hội chợ vui chơi;goal=bàn thắng;hop=nhảy lò cò;ice skates=giày trượt băng;ice skating=môn trượt băng;model=mô hình;net=lưới;party=bữa tiệc;pirate=cướp biển;player=người chơi;pool=bể bơi;pop star=ngôi sao nhạc pop;present=quà tặng;roller skates=giày trượt patin;roller skating=môn trượt patin;sail=buồm, đi thuyền buồm;score=ghi điểm;skate=trượt patin hoặc băng;skip=nhảy dây;swimming pool=bể bơi;treasure=kho báu`],
    ['movers', 'weather', 6, `cloud=mây;cloudy=nhiều mây;ice=băng;rain=mưa;rainbow=cầu vồng;snow=tuyết;sunny=có nắng;weather=thời tiết;wind=gió;windy=có gió`],
    ['movers', 'time', 6, `after=sau;before=trước;Friday=thứ Sáu;holiday=kỳ nghỉ;last=cuối, trước đó;Monday=thứ Hai;o'clock=giờ đúng;Saturday=thứ Bảy;Sunday=Chủ nhật;Thursday=thứ Năm;ticket=vé;travel=du lịch;trip=chuyến đi;Tuesday=thứ Ba;Wednesday=thứ Tư;week=tuần;weekend=cuối tuần;yesterday=hôm qua`],
    ['movers', 'body', 7, `back=lưng, phía sau;beard=râu;blond=tóc vàng;curly=xoăn;fair=sáng màu (tóc, da);fat=béo;moustache=ria mép;neck=cổ;shoulder=vai;stomach=bụng;straight=thẳng;thin=gầy, mỏng;tooth=răng`],
    ['movers', 'clothes', 7, `coat=áo khoác dài;helmet=mũ bảo hiểm;scarf=khăn quàng;sweater=áo len;swimsuit=đồ bơi;pair=đôi, cặp`],
    ['movers', 'description', 7, `afraid=sợ;all right=ổn;asleep=đang ngủ;awake=thức;bad=tệ;badly=một cách tệ;best=tốt nhất;better=tốt hơn;boring=nhàm chán;brave=dũng cảm;brilliant=rất tuyệt;busy=bận;careful=cẩn thận;carefully=một cách cẩn thận;clever=thông minh;dangerous=nguy hiểm;different=khác nhau;difficult=khó;dry=khô, làm khô;easy=dễ;exciting=thú vị;famous=nổi tiếng;frightened=hoảng sợ;hot=nóng;huge=khổng lồ;little=nhỏ, ít;loud=ồn, to tiếng;loudly=một cách to tiếng;naughty=nghịch ngợm;pretty=xinh;quick=nhanh;quickly=một cách nhanh chóng;quiet=yên lặng;quietly=một cách yên lặng;safe=an toàn;slow=chậm;slowly=một cách chậm chạp;strong=khỏe;surprised=ngạc nhiên;sweet=ngọt;tall=cao;terrible=rất tệ;weak=yếu;wet=ướt;worse=tệ hơn;worst=tệ nhất;wrong=sai`],
    ['movers', 'actions', 8, `be called=được gọi là;bring=mang đến;build=xây;buy=mua;call=gọi;carry=mang, xách;change=thay đổi;climb=leo;cook=đầu bếp, nấu ăn;could=đã có thể;dream=giấc mơ, mơ;dress up=hóa trang;drop=làm rơi;feed=cho ăn;fix=sửa;get dressed=mặc quần áo;get off=xuống xe;get on=lên xe;get undressed=cởi quần áo;get up=thức dậy;go shopping=đi mua sắm;grow=lớn lên, trồng;have to=phải;help=giúp;hide=trốn, giấu;invite=mời;laugh=cười;look for=tìm kiếm;lose=làm mất, thua;mean=có nghĩa là;move=di chuyển;need=cần;put on=mặc vào;send=gửi;shop=mua sắm;shout=hét;take=lấy, mang;take off=cởi ra;think=nghĩ;wait=chờ;wake up=thức giấc;wash=rửa;water=tưới nước;work=làm việc, công việc`],
    ['movers', 'language', 8, `address=địa chỉ;age=tuổi;all=tất cả;always=luôn luôn;another=một cái khác;any=bất kỳ;because=bởi vì;both=cả hai;come on=nào, cố lên;every=mỗi;everyone=mọi người;everything=mọi thứ;excuse me=xin phép, xin lỗi;how much=bao nhiêu (giá, lượng);how often=bao lâu một lần;idea=ý tưởng;kind=loại;more=nhiều hơn;most=nhiều nhất;must=phải;never=không bao giờ;noise=tiếng ồn;nothing=không có gì;often=thường xuyên;only=chỉ;seat=chỗ ngồi;shall=dùng để đề nghị;shopping=việc mua sắm;someone=ai đó;something=điều gì đó;sometimes=thỉnh thoảng;than=hơn;when=khi nào;why=tại sao;would=dùng trong lời mời hoặc mong muốn`]
  ];
  const topics = {family:'Gia đình', home:'Ngôi nhà', school:'Trường học & công nghệ', animals:'Động vật', nature:'Thiên nhiên', food:'Ăn uống', health:'Sức khỏe', town:'Thành phố', position:'Vị trí', transport:'Phương tiện', sport:'Thể thao & sở thích', weather:'Thời tiết', time:'Thời gian & kỳ nghỉ', body:'Cơ thể', clothes:'Quần áo', description:'Miêu tả', actions:'Hành động', language:'Từ giao tiếp', numbers:'Số & chữ cái', names:'Tên riêng'};
  const aliases = {apartment:['flat'], eraser:['rubber'], candy:['sweet','sweets'], chips:['fries'], colour:['color'], favourite:['favorite'], football:['soccer'], grey:['gray'], lorry:['truck'], shop:['store'], television:['TV'], 'teddy bear':['teddy'], 'take a photo':['take a picture'], child:['children'], man:['men'], woman:['women'], person:['people'], mouse:['mice'], foot:['feet'], leaf:['leaves'], tooth:['teeth'], parent:['parents'], vegetable:['vegetables'], pancake:['pancakes'], blond:['blonde'], elevator:['lift'], centre:['center'], 'city centre':['city center'], 'town centre':['town center'], 'shopping centre':['shopping center'], 'sports centre':['sports center'], film:['movie'], 'film star':['movie star'], 'have to':['have got to'], 'wake up':['wake'], stairs:['stair']};
  const entries = groups.flatMap(([level, topic, week, rows]) => rows.split(';').map(row => {
    const [raw, meaning] = row.trim().split('=');
    const word = raw.trim().replace('basebalL', 'baseball');
    const id = 'lex-' + level + '-' + word.toLowerCase().replace(/[^a-z0-9]+/g, '-');
    return {id, word, meaning:meaning.trim(), level, topic, week, aliases:aliases[word] || [], example:'', emoji:''};
  }));
  // Distinct meanings remain separate, even when the spelling is identical.
  entries.push({id:'lex-starters-bat-sport',word:'bat',meaning:'gậy đánh bóng',level:'starters',topic:'sport',week:5,aliases:[],example:'Hit the ball with the bat.'});
  entries.push({id:'lex-starters-mouse-computer',word:'mouse',meaning:'chuột máy tính',level:'starters',topic:'school',week:1,aliases:[],example:'The mouse is next to the keyboard.'});
  entries.push({id:'lex-movers-floor-storey',word:'floor',meaning:'tầng của tòa nhà',level:'movers',topic:'home',week:1,aliases:[],example:'Our classroom is on the first floor.'});
  const names = {starters:'Alex Alice Ann Anna Ben Bill Dan Eva Grace Hugo Jill Kim Lucy Mark Matt May Nick Pat Sam Sue Tom', movers:'Charlie Clare Daisy Fred Jack Jane Jim Julia Lily Mary Paul Peter Sally Vicky Zoe'};
  Object.entries(names).forEach(([level, list]) => list.split(' ').forEach(word => entries.push({id:`lex-name-${word.toLowerCase()}`,word,meaning:`tên riêng ${word}`,level,topic:'names',week:7,aliases:[],example:`My name is ${word}.`})));
  const units = ['zero','one','two','three','four','five','six','seven','eight','nine','ten','eleven','twelve','thirteen','fourteen','fifteen','sixteen','seventeen','eighteen','nineteen'];
  const tens = ['','','twenty','thirty','forty','fifty','sixty','seventy','eighty','ninety'];
  for (let n=1;n<=100;n++) {
    const word = n === 100 ? 'one hundred' : n < 20 ? units[n] : tens[Math.floor(n/10)] + (n%10 ? '-'+units[n%10] : '');
    entries.push({id:`lex-number-${n}`,word,meaning:`số ${n}`,level:n<=20?'starters':'movers',topic:'numbers',week:7,aliases:n===100?['hundred','a hundred']:[],example:`The number is ${word}.`});
  }
  'first second third fourth fifth sixth seventh eighth ninth tenth eleventh twelfth thirteenth fourteenth fifteenth sixteenth seventeenth eighteenth nineteenth twentieth'.split(' ').forEach((word,i)=>entries.push({id:`lex-ordinal-${i+1}`,word,meaning:`thứ ${i+1}`,level:'movers',topic:'numbers',week:7,aliases:[],example:`This is the ${word} picture.`}));
  const examples = {
    kitten:'The kitten is sleeping in a box.', puppy:'My puppy has got small ears.', penguin:'The penguin is swimming.', snail:'The snail is on a leaf.',
    coat:'Put on your coat. It is cold.', scarf:'This scarf is yellow.', sweater:'My sweater is blue.', swimsuit:'My swimsuit is in my bag.',
    neck:'The giraffe has got a long neck.', shoulder:'A parrot is on his shoulder.', stomach:'My stomach hurts.', tooth:'I have got a loose tooth.',
    bowl:'The soup is in a bowl.', plate:'Put the sandwich on a plate.', hungry:'I am hungry. Can I have an apple?', thirsty:'I am thirsty. I would like some water.',
    dentist:'The dentist is looking at my teeth.', nurse:'The nurse works at the hospital.', earache:'I have got an earache.', temperature:'The nurse takes my temperature.',
    'get on':'We get on the bus here.', 'get off':'We get off the bus near school.', 'put on':'Put on your shoes.', 'take off':'Take off your coat.',
    always:'I always brush my teeth in the morning.', often:'We often walk to school.', sometimes:'I sometimes eat rice for breakfast.', never:'I never swim alone.',
    first:'This is my first English book.', because:'I am happy because my friend is here.', before:'Wash your hands before dinner.', after:'We play after school.',
    fly:'The birds can fly.', bat:'A bat flies at night.', leaf:'A leaf is falling from the tree.', would:'Would you like some water?', shall:'Shall we play a game?'
  };
  entries.forEach(v => {if (examples[v.word] && !v.example) v.example=examples[v.word];});
  entries.find(v=>v.id==='lex-movers-fly').example='There is a fly on the window.';
  // One canonical bank entry can cover a headword's listed noun and verb uses.
  window.MoversLexicon = {entries, topics, source:'https://www.cambridgeenglish.org/Images/506166-starters-movers-flyers-word-list-2025.pdf', edition:'2025'};
})();
